### ISSUE TITLE
Laravel 5.7 Support

### ISSUE THREAD

**Issue by calvinps** [vrajroham/laravel-flock-notification#2]
I'm not able to install via composer because I'm running on laravel 5.7. Looks like this is locked onto versions 5.5 or 5.6. Can you update composer to allow for apps running on current (and future) versions of Laravel to install?

**Comment by vrajroham** [comment]
@calvinps Thanks for reporting. I'll try to fix this ASAP.

**Comment by vrajroham** [comment]
@calvinps New release has been tagged. Now you can use it at 5.7.* 

https://github.com/vrajroham/laravel-flock-notification/releases/tag/1.0.2

**Comment by calvinps** [comment]
@vrajroham thanks! I looks like something still needs to be done to release it on packagist though - it's not showing release 1.0.2 or the changes on dev-master. https://packagist.org/packages/vrajroham/laravel-flock-notification#dev-master

**Comment by vrajroham** [comment]
@calvinps It takes some time to update on packagist once released. I can see the updated tag on packagist now. https://packagist.org/packages/vrajroham/laravel-flock-notification#1.0.2. 

Please close this issue once you get it running.

Thanks for patience. :)

**Comment by calvinps** [comment]
Got it now, thanks. Great package, works great!
